name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: 'Lisa'
      - name: Test Javascript Hello Action with custom name
        uses: adeloyedeji/github-actions-hello@v1.0
